### ISSUE TITLE
PHPStorm 2020.1 - .env.* not highlighting

### ISSUE THREAD

**Issue by pmcgoverncw** [adelf/idea-php-dotenv-plugin#53]
Since installing PHPStorm 2020.1, .env.* files are not highlighting (ex: .env.local)

![Screen Shot 2020-04-14 at 12 21 19 PM](https://user-images.githubusercontent.com/51176015/79254815-e998b400-7e4a-11ea-9e22-0f6ff334ad5a.png)
![Screen Shot 2020-04-14 at 12 21 48 PM](https://user-images.githubusercontent.com/51176015/79254817-eac9e100-7e4a-11ea-8601-87f144a39546.png)
![Screen Shot 2020-04-14 at 12 22 10 PM](https://user-images.githubusercontent.com/51176015/79254818-eac9e100-7e4a-11ea-99f9-2d3793bfcd2c.png)
![Screen Shot 2020-04-14 at 12 22 49 PM](https://user-images.githubusercontent.com/51176015/79254819-eac9e100-7e4a-11ea-91be-542b98c99ae8.png)
![Screen Shot 2020-04-14 at 12 23 08 PM](https://user-images.githubusercontent.com/51176015/79254820-eb627780-7e4a-11ea-83ef-af2cef5a7fe2.png)

**Comment by adelf** [comment]
https://youtrack.jetbrains.com/issue/WI-52299

**Comment by jezmck** [comment]
You'll need to remove any `.env` matching patterns from the **Text** file type in Preferences > Editor > File Types.

**Comment by adelf** [comment]
Yes. Thank you. Jetbrains made a little mistake and all these Text file
type linkings will be removed in the next version 2020.1.1 . But it can be
fixed manually in Settings | Editor | File types | Text - and remove all
.env.* from there.

**Comment by dmydlo** [comment]
Note:
If for you it still doesn't work, you might (as I had) have an additional type of files "Env" besides ".env" which comes from EnvFile plugin.

**Comment by pmcgoverncw** [comment]
Thanks everyone - I was able to remove it from the text file types and all is well now.
Anyone know if there are plans for native .env support/highlighting in PHPStorm?

**Comment by adelf** [comment]
> Anyone know if there are plans for native .env support/highlighting in PHPStorm?

Whats wrong with this plugin? :)

**Comment by pmcgoverncw** [comment]
@adelf Nothing at all - but the more prevalent some features become, the more they should be considered for direct integration into the IDE. Multiple widely-adopted PHP frameworks are natively using .env files, so it makes sense to have native support in a PHP IDE.
(and if I missed any sarcasm... sorry lol)

**Comment by adelf** [comment]
One of the main conceptions of IntelliJ IDE's are plugins. This plugin makes completion for environment variables for PHP, Ruby, Python, Go and Javascript languages. So, if JetBrains decide to implement something in their side, implementation will be very close to this plugin :)

**Comment by pmcgoverncw** [comment]
I would argue further, but PHPStorm auto-suggests relevant plugins when it detects use for them, so I have no argument. :)
